host: 0.0.0.0
port: 1885
server.port: 13444
websocket_port: 1883

micrometer.enable: true

management:
  endpoint:
    health:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: prometheus,info,health

logging.level.io.moquette.interception: DEBUG
spring:
# Configuration of RabbitMQ
  rabbitmq:
    host: 10.66.0.1
    port: 5672
    username: guest
    password: guest
# Configuration of Google Cloud. Is relevant in case of using Google PubSub
#  cloud:
#    gcp:
#      project-id: emtdev-184813
#      credentials:
#        #location: file:///home/rico/.gcloud/emtdev-efd77f4bf0eb.json
#        location: file:///home/rico/.gcloud/emtdev-ca5c5c2614d4.json
#        scopes: DEFAULT_SCOPES,https://www.googleapis.com/auth/pubsub,https://www.googleapis.com/auth/cloud-platform
